layout: stacked
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  facebook: abhinavsri360
  hackerrank: abhinavsri360
  instagram: abhinavsri360
  # keybase: your_username
  linkedin: abhinav-srivastava-a9b238172
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  telegram: abhinavsri360
  twitter: abhinavsri360
  # unsplash: your_username
  # vk: your_username
  website: https://gitstats.me/abhinavsri360
  # youtube: your_username

topics:
  - name: React
    web_url: https://github.com/topics/react
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/react/react.png

  - name: Docker
    web_url: https://github.com/topics/docker
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/docker/docker.png

  - name: Vue.js
    web_url: https://github.com/topics/vue
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/vue/vue.png

  - name: MongoDB
    web_url: https://github.com/topics/mongodb
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/mongodb/mongodb.png

  - name: GitHub
    web_url: https://github.com/topics/github
    image_url: https://raw.githubusercontent.com/github/explore/78df643247d429f6cc873026c0622819ad797942/topics/github/github.png

  - name: Flutter
    web_url: https://github.com/topics/flutter
    image_url: https://raw.githubusercontent.com/github/explore/cebd63002168a05a6a642f309227eefeccd92950/topics/flutter/flutter.png
